### ISSUE TITLE
meaning of rectangles.zip

### ISSUE THREAD

**Issue by laisimiao** [alanlukezic/d3s#28]
Hi @alanlukezic Thank you for your work.
When training d3s, I don't know the meaning of rectangles.zip you provide us.
Taking `groundtruth-1.txt` for example, does each row means [xmin,ymin,weight,height] of object1 in that sequence?
Look forward to your reply!

**Comment by alanlukezic** [comment]
Since the groundtruth in YT-VOS dataset is given as a segmentation mask and a target bounding box is required for training as well, we provide this information in the groundtruth-*.txt files. Exactly as you said, each row represents an axis-aligned bounding box of the object, which is encoded with 1 in the groundtruth segmentation mask.

**Comment by laisimiao** [comment]
Ok, thank you!
