### ISSUE TITLE
Why distance map L is a inversed-guass-model?

### ISSUE THREAD

**Issue by sherlockedlee** [alanlukezic/d3s#3]
Thanks for your brilliant work.I have trouble understanding the refinement pathway.The input F,P focus on the object,what is the consideration of L which has higher response in the background?And it's really confusing if L has higher response in the foreground,after training,tracker behave worser than yours.

**Comment by alanlukezic** [comment]
That is how L is defined - distance transform on the position of the maximum correlation response represents estimation of the target position. It would be possible to set 1 on the position of the maximum and then gradually decrease the value when going further from that position, but the network is currently trained so that there is a minimum on target position.

**Comment by sherlockedlee** [comment]
> That is how L is defined - distance transform on the position of the maximum correlation response represents estimation of the target position. It would be possible to set 1 on the position of the maximum and then gradually decrease the value when going further from that position, but the network is currently trained so that there is a minimum on target position.

Thanks.
